export enum RejectionReasons {
  missingDocumentPhoto = 'MISSING_DOCUMENT_PHOTO',
  documentNotAccepted = 'DOCUMENT_NOT_ACCEPTED',
  dataDoesNotMatch = 'DATA_DOES_NOT_MATCH',
  sanctioned = 'SANCTIONED',
  missingSelfiePhoto = 'MISSING_SELFIE_PHOTO',
  facesDoesNotMatch = 'FACES_DOES_NOT_MATCH',
  poorPhotoQuality = 'POOR_PHOTO_QUALITY',
  poorPhotoLighting = 'POOR_PHOTO_LIGHTING',
  blurredPhoto = 'BLURRED_PHOTO',
  badMediaFormat = 'BAD_MEDIA_FORMAT',
  miscellaneous = 'MISCELLANEOUS',
  possibleFraudAttempt = 'POSSIBLE_FRAUD_ATTEMPT',
  unrelatedPhoto = 'UNRELATED_PHOTO',
  moreThanOnePerson = 'MORE_THAN_ONE_PERSON',
  prohibitedCountryOrState = 'PROHIBITED_COUNTRY_OR_STATE',
  documentIsExpired = 'DOCUMENT_IS_EXPIRED',
  documentWithNonLatinCharacters = 'DOCUMENT_WITH_NON_LATIN_CHARACTERS',
  partOfDocumentIsCovered = 'PART_OF_DOCUMENT_IS_COVERED',
  nameMismatch = 'NAME_MISMATCH',
  expirationDateMismatch = 'EXPIRATION_DATE_MISMATCH',
  incorrectInformationProvided = 'INCORRECT_INFORMATION_PROVIDED',
  partOfFaceIsCovered = 'PART_OF_FACE_IS_COVERED',
  underagePerson = 'UNDERAGE_PERSON',
  prohibitedNationality = 'PROHIBITED_NATIONALITY',
  docAndBioAgeDoesntMatch = 'DOC_AND_BIO_AGE_DOESNT_MATCH',
  duplicatedInfo = 'DUPLICATED_INFO',
}

export const CriticalReasons: RejectionReasons[] = [
  RejectionReasons.sanctioned,
  RejectionReasons.miscellaneous,
  RejectionReasons.possibleFraudAttempt,
  RejectionReasons.prohibitedCountryOrState,
  RejectionReasons.underagePerson,
  RejectionReasons.prohibitedNationality,
  RejectionReasons.docAndBioAgeDoesntMatch,
  RejectionReasons.duplicatedInfo,
];
